apiVersion: v1 
kind: Pod 
metadata:   
  creationTimestamp: null   
  labels:     
    run: use-pv   
  name: use-pvspec-tony
spec: 
  containers:   
  - image: nginx     
    name: use-pv
    volumeMounts:
    - mountPath: '/data'
      name: pv-1  
    resources: {}   
  dnsPolicy: ClusterFirst   
  restartPolicy: Always
status: {}