apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: messaging-service
  name: messaging-service
spec:
  ports:
  - name: 6379-80
    port: 6379
    protocol: TCP
    targetPort: 80
  selector:
    tier: msg
  type: ClusterIP
status:
  loadBalancer: {}
