apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ''
  hostPath:
    path: /data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-1
spec:
  storageClassName: ''
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1 
kind: Pod 
metadata:   
  creationTimestamp: null   
  labels:     
    run: use-pv   
  name: use-pvspec-tony
spec: 
  volumes:
    - name: pvc-storage
      persistentVolumeClaim:
        claimName: pvc-1
  containers:   
  - image: nginx     
    name: use-pv
    volumeMounts:
    - mountPath: /data
      name: pvc-storage
    resources: {}   
  dnsPolicy: ClusterFirst   
  restartPolicy: Always
status: {}
