apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: redis-storage-tony
  name: redis-storage-tony
spec:
  containers:
  - image: redis:alpine
    name: redis-storage-tony
    volumeMounts:
    - mountPath: '/data/redis'
      name: redis-volume
  volumes:
  - name: redis-volume
    emptyDir:
      sizeLimit: 500Mi
