apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: static-busybox
  name: static-busybox
spec:
  nodeSelector:
    node-role.kubernetes.io/control-plane: ''
  containers:
  - image: busybox
    name: static-busybox
    command: ["sleep"]
    args: ["1000"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
