apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-analytics
  labels:
    app: pv-analytics
spec:
  storageClassName: default
  volumeMode: Filesystem
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /pv/data-analytics