apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dev
  labels:
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
      - name: nginx
        image: nginx
        resources: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-prod
  labels:
    env: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
      - name: nginx
        image: nginx
        resources: {}