apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-specific-node
  name: nginx-specific-node
spec:
  nodeSelector:
    nodeName: nginxnode
  containers:
  - image: nginx
    name: nginx-specific-node
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
